# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks: 
    -   id: trailing-whitespace
        alias: trim-wsp
        name: Trim Trailing Whitespace
        description: This hook trims trailing whitespace
        types: [python]
        verbose: true
    -   id: requirements-txt-fixer
        alias: req-fix
        name: Requirements.txt Fixer
    -   id: fix-encoding-pragma

-   repo: https://github.com/psf/black.git
    rev: 22.3.0
    hooks:
    -   id: black
        name: Black Formatting
        description: Format ptyhon code using black
        verbose: true

-   repo: https://github.com/pre-commit/mirrors-mypy.git
    rev: v0.961
    hooks:
    -   id: mypy
        files: ^src
        args: []

-   repo: https://github.com/PyCQA/flake8.git
    rev: 4.0.1
    hooks:
    -   id: flake8
        name: Flake 8
        args: []
